name: Deploy Terraform to AWS

on:
  push:
    branches:
      - main  # Chạy khi có thay đổi trên nhánh main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Thiết lập AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  # Đảm bảo sử dụng đúng `region`

      # Bước 3: Thiết lập Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8  # Phiên bản Terraform phù hợp với dự án của bạn

      # Bước 4: Khởi tạo Terraform
      - name: Initialize Terraform
        run: terraform init

      # Bước 5: Kiểm tra định dạng của mã Terraform
      - name: Format Terraform code
        run: terraform fmt -check

      # Bước 6: Kiểm tra hợp lệ của mã Terraform
      - name: Validate Terraform code
        run: terraform validate

      # Bước 7: Lập kế hoạch triển khai Terraform
      - name: Plan Terraform
        env:
          AWS_REGION: us-west-2  # Đảm bảo sử dụng đúng `region`
        run: terraform plan -out=plan.tfplan

      # Bước 8: Áp dụng mã Terraform chỉ khi có thay đổi trên nhánh main
      - name: Apply Terraform (only on push to main)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_REGION: us-west-2  # Đảm bảo sử dụng đúng `region`
        run: terraform apply -auto-approve plan.tfplan
